version: "3.5"

services:
  pg:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    container_name: postgres
    ports:
      - "5430:5432"

  app:
    build: .
    restart: unless-stopped
    depends_on:
      - pg
    ports:
      - "3060:3060"